export default[
    {
      "_id": "Q101",
      "course": "RS101",
      "title": "Rocket Propulsion Fundamentals Quiz",
      "description": "Test your understanding of basic rocket propulsion concepts",
      "published": true,
      "due": "2024-06-15",
      "type": "GRADEDQUIZ",
      "availableFrom": "2024-06-01",
      "until": "2024-06-16",
      "points": 100,
      "assignmentGroup": "QUIZZES",
      "shuffleAns": true,
      "timeLmt": 30,
      "multipleAttempts": true,
      "viewResponses": true,
      "showCorrectAnswers": true,
      "oneQaTime": true,
      "lockdownBrowser": false,
      "viewResults": true,
      "webcam": false,
      "lockQafterA": false,
      "accessCode": "",
      "maxAttempts": 3
    },
    {
      "_id": "Q102",
      "course": "RS101",
      "title": "Combustion Processes Quiz",
      "description": "Quiz on combustion chemistry and efficiency",
      "published": true,
      "due": "2024-06-22",
      "type": "GRADEDQUIZ",
      "availableFrom": "2024-06-10",
      "until": "2024-06-23",
      "points": 75,
      "assignmentGroup": "QUIZZES",
      "shuffleAns": false,
      "timeLmt": 45,
      "multipleAttempts": false,
      "viewResponses": true,
      "showCorrectAnswers": false,
      "oneQaTime": true,
      "lockdownBrowser": false,
      "viewResults": true,
      "webcam": false,
      "lockQafterA": true,
      "accessCode": "",
      "maxAttempts": 1
    },
    {
      "_id": "Q201",
      "course": "RS102",
      "title": "Aerodynamics Basics Quiz",
      "description": "Test on fluid dynamics and airflow principles",
      "published": true,
      "due": "2024-06-18",
      "type": "GRADEDQUIZ",
      "availableFrom": "2024-06-05",
      "until": "2024-06-19",
      "points": 80,
      "assignmentGroup": "QUIZZES",
      "shuffleAns": true,
      "timeLmt": 60,
      "multipleAttempts": true,
      "viewResponses": true,
      "showCorrectAnswers": true,
      "oneQaTime": false,
      "lockdownBrowser": false,
      "viewResults": true,
      "webcam": false,
      "lockQafterA": false,
      "accessCode": "",
      "maxAttempts": 2
    },
    {
      "_id": "Q301",
      "course": "RS103",
      "title": "Spacecraft Design Principles",
      "description": "Assessment on spacecraft structural design",
      "published": true,
      "due": "2024-06-20",
      "type": "GRADEDQUIZ",
      "availableFrom": "2024-06-08",
      "until": "2024-06-21",
      "points": 90,
      "assignmentGroup": "EXAMS",
      "shuffleAns": true,
      "timeLmt": 90,
      "multipleAttempts": false,
      "viewResponses": false,
      "showCorrectAnswers": false,
      "oneQaTime": true,
      "lockdownBrowser": true,
      "viewResults": false,
      "webcam": true,
      "lockQafterA": true,
      "accessCode": "SPACE2024",
      "maxAttempts": 1
    },
    {
      "_id": "Q401",
      "course": "RS104",
      "title": "Organic Chemistry Structures Quiz",
      "description": "Quiz on molecular structures and bonding",
      "published": true,
      "due": "2024-06-12",
      "type": "PRACTICEQUIZ",
      "availableFrom": "2024-06-01",
      "until": "2024-06-13",
      "points": 50,
      "assignmentGroup": "QUIZZES",
      "shuffleAns": false,
      "timeLmt": 0,
      "multipleAttempts": true,
      "viewResponses": true,
      "showCorrectAnswers": true,
      "oneQaTime": false,
      "lockdownBrowser": false,
      "viewResults": true,
      "webcam": false,
      "lockQafterA": false,
      "accessCode": "",
      "maxAttempts": 5
    }
  ];